name: insight
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - flask=3.0.3
  - flask-jwt-extended=4.6.0
  - flask-smorest=0.44.0
  - flask-sqlalchemy=3.1.1
  - marshmallow=3.21.3
  - psycopg2=2.9.9
  - python=3.12
  - sqlalchemy=2.0.32
  - transformers=4.44.2
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - pip:
      - amazoncaptcha==0.5.11
      - pillow>=9.0.1,<9.6.0
      - flask-executor
      - playwright==1.46.0
      - playwright-stealth==1.0.6
      - fake-useragent==1.5.1
      - pytz==2024.1
      - pgvector==0.3.2
